name: three-gen-prompt-generator
channels:
  - defaults
  - conda-forge
  - nvidia
  
dependencies:
  - python=3.10
  - pip
  - cuda-toolkit=12.1.1
  - pip:
    - numpy
    - torch
    - torchvision
    - "--extra-index-url https://download.pytorch.org/whl/cu121"
    - huggingface_hub
    - transformers
    - protobuf
    - tqdm
    - pytest
    - groq
    - accelerate
    - loguru==0.*
    - vllm
    - flash-attn