name: three_gen_prompt_generator
channels:
  - defaults
  - conda-forge
  - nvidia
  
dependencies:
  - python=3.10
  - pip
  - cuda-toolkit=12.1.1
  - pip:
    - numpy==1.23.0
    - torch==2.1.1
    - torchvision
    - "--extra-index-url https://download.pytorch.org/whl/cu121"
    - huggingface_hub>=0.19.4
    - transformers>=4.38.2
    - protobuf>=4.21.0,<5.0.0
    - colorama
    - tqdm
    - pytest
    - groq
    - symspellpy
    - accelerate
    - bitsandbytes
