name: three-gen-prompt-generator
channels:
  - defaults
  - conda-forge
  - nvidia
  
dependencies:
  - python=3.10
  - pip
  - cuda-toolkit=12.1.1
  - pip:
    - numpy==1.*
    - torch==2.1.1
    - torchvision
    - "--extra-index-url https://download.pytorch.org/whl/cu121"
    - huggingface_hub==0.*
    - transformers==4.*
    - protobuf==4.40.*
    - tqdm
    - pytest
    - groq
    - symspellpy
    - accelerate
    - bitsandbytes
    - loguru==0.*
    - vllm
    - langchain